BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'clear'
    Button:
        text: 'two'
    Button:
        text: 'three'
    Button:
    text: 'three'
    color: (1, 1, 0, 1)
Label:
    text: 'Enter your name'
    Button:
    text: 'Greet'
    on_press: app.handle_greet()
    Label:
        id: output_label
        text: 'Harley'
        color: (1, 1, 0, 1)